#!/usr/bin/env python
import argparse
from math import pow
import os
import resource
import subprocess
import sys
import time
from threading import Thread

MEBIBYTE = pow(2, 20)
GIBIBYTE = pow(2, 30)

def monitor(pid):
    "Monitor the resources used by another process"
    i = 0
    good = False
    page_size = os.sysconf('SC_PAGE_SIZE') 
    
    # Try to open /proc/PID/statm once every 10ms.  Give up after 10 sec.
    while i < 100:
        time.sleep(0.01)
        try:
            print "monitor: trying "
            p = open('/proc/{}/statm'.format(pid), 'r')
            mem = p.readline().split()
            good = True
            break
        except IOError, e:
            if e[0] == 2: # no such file or directory
                i += 1
                continue
            else:
                raise
    if not good:
        print "monitor: failed to get process stats"
        return
    # man proc(5) for statm format
    memtotal = round((int(mem[0]) * page_size) / MEBIBYTE, 3)
    memresident = round((int(mem[1]) * page_size) / MEBIBYTE, 3)
    print 'Pid {}: mem total: {} MiB RSS: {} MiB'.format(pid, memtotal, memresident)
    p.close()
    
parser = argparse.ArgumentParser(description='Measure compression performance')
parser.add_argument('file', metavar='FILE', help='path to input file')
args = parser.parse_args()

if not os.path.isfile(args.file):
    raise DataFileError('{} is not a file'.format(args.file))
in_path = os.path.abspath(args.file)
in_filename = os.path.basename(args.file)
in_size = round(os.stat(args.file).st_size / GIBIBYTE, 2)

out_dir = '/var/tmp'
prog = 'pigz'
opt = '-c'
level = 1

for level in range(1,10):
    out_path = '{}/{}-{}-{}'.format(out_dir, in_filename, prog, level)
    out = open(out_path, 'wb')

    start = time.time()
    command = [prog, opt, '-{}'.format(level), in_path]
    comp = subprocess.Popen(command, stdout=out)
    #print "subproc {} compressing {} GiB at level {}...".format(comp.pid, in_size, level)
    t = Thread(target=monitor, args=(comp.pid,))
    t.start()
    comp.wait()
    end = time.time()
    elapsed = end - start
    if comp.returncode != 0:
        print 'error: command returned {}'.format(comp.returncode)
        sys.exit(2)
    out.close()
    out_size = round(os.stat(out_path).st_size / GIBIBYTE, 2)
    #print 'done. compressed output is {} GiB'.format(out_size)
    #print 'comp ratio: {}'.format(out_size / in_size)
    print '{},{},{},{},{},{}'.format(prog, level, in_size, out_size, round(out_size / in_size, 2), round(elapsed,1))
